#ifndef SHAREDDEFS_H
#define SHAREDDEFS_H

enum ShaderType_t
{
	SHADERTYPE_LIT = 0,
	SHADERTYPE_UNLIT,
	SHADERTYPE_SKYBOX,
	SHADERTYPE_DEPTH,
	SHADERTYPE_SHADOW,
	SHADERTYPE_COLORHUD,

	SHADERTYPE_COUNT,
	SHADERTYPE_INVALID = SHADERTYPE_COUNT,
};

static const char *g_sShaderNames[] =
{
	"lit",
	"unlit",
	"skybox",
	"depth",
	"shadow",
	"colorhud",
};

enum ShaderSubType_t
{
	SHADERSUBTYPE_DEFAULT = 0,
	SHADERSUBTYPE_DIR,
	SHADERSUBTYPE_POINT,
	SHADERSUBTYPE_SPOT,
	SHADERSUBTYPE_CSM,
	SHADERSUBTYPE_COUNT,
};

enum ShaderQuality_t
{
	SHADERQUALITY_DEFAULT = 0,
	SHADERQUALITY_LOW,
	SHADERQUALITY_MEDIUM,
	SHADERQUALITY_HIGH,
	SHADERQUALITY_ULTRA,
	SHADERQUALITY_COUNT,
};

ShaderType_t UTIL_ShaderNameToType( const char *sShaderName );
const char *UTIL_ShaderTypeToName( ShaderType_t tShaderType );

enum RenderPass_t
{
	RENDERPASS_DEPTH = 0,
	RENDERPASS_UNLIT,
	RENDERPASS_LIT,
	RENDERPASS_SHADOW,
	RENDERPASS_HUD,
};

#define FL_RENDERPASS_DEPTH		(1 << RENDERPASS_DEPTH)
#define FL_RENDERPASS_UNLIT		(1 << RENDERPASS_UNLIT)
#define FL_RENDERPASS_LIT		(1 << RENDERPASS_LIT)
#define FL_RENDERPASS_SHADOW	(1 << RENDERPASS_SHADOW)
#define FL_RENDERPASS_HUD		(1 << RENDERPASS_HUD)

#endif // SHAREDDEFS_H